### ISSUE TITLE
bazel build (iOS APP with swift)

### ISSUE THREAD

**Issue by salim-boudriiya** [acecilia/BazelVSBuckSample#1]
Hi @acecilia ,

I am working on a project to build an ios (Xcode) application using swift, and I have several problems when creating the build files to do this construction with bazel.

I wanted to ask you if you have any example in which I can look to do this exercise.

Best regards

**Comment by acecilia** [comment]
Hi @salim-boudriiya:

I think you can start by going though the official tutorial here: https://docs.bazel.build/versions/master/tutorial/ios-app.html

After you mastered that tutorial, you can have a look at other bazel setups, like the one in this repo. Others I know about are https://github.com/material-components/material-components-ios and https://github.com/lyft/envoy-mobile

**Comment by salim-boudriiya** [comment]
Thank you for your help !!
